### ISSUE TITLE
use separate specialized variable instead of "updatetime"

### ISSUE THREAD

**Issue by towc** [RRethy/vim-illuminate#1]
Hi! Great idea for a plugin, but I was confused that the search was taking so long when I first tried it, until I read the docs here and it mentioned that it was waiting for `updatetime` ms before highlighting. In my vimrc, I happened to have `updatetime` set to 4s, and I don't see a reason why the delay for writing to a swap file should be linked to the highlighting delay.

Could you use something like `g:Illuminate_delay` which defaults to `100` or similar?

**Comment by RRethy** [comment]
Hey! `updatetime` is the value used for the CursorHold autocmd which is the autocmd that drives the illumination. I like the idea however of the variable as the delay since it offers a decoupling from the CursorHold autocmd the user might be using for other things, the only weird thing is implementation since I would have to move away from CursorHold and use CursorMoved then keep track of time since last illumination which I'm open to do as long as it results in no overhead. I'll try it out and get back to you 👍

**Comment by RRethy** [comment]
Added support for g:Illuminate_delay using timers to avoid reliance on updatetime and CursorHold. Default time is 250 millis. #2
