### ISSUE TITLE
.configure should be .setup

### ISSUE THREAD

**Issue by Diablo-D3** [RRethy/vim-illuminate#112]
Most Neovim Lua plugins are choosing to name their init entry point as `.setup`, not `.configure`, especially in the nvim-lsp ecosystem.

**Comment by RRethy** [comment]
The history of why plugins use `.setup` is because of [this article by norcalli](https://github.com/norcalli/neovim-plugin). After that was published a bunch of plugin developers starting following that until it just became a thing everyone did without thinking about it. It's was a bad idea then and it's a bad idea now. Having to install a plugin and call `require('plugin_name').setup({})` a bunch of times in your config is pointless. If we look at traditional Vim plugins (see every tpope plugin), installing them is sufficient to get them to work, no useless one-liner call to `.setup` needed.

In terms of the name `.configure`, it's to distinguish from the fact that it doesn't start anything, you can omit `.configure` and the plugin will still start up. This is different to how `.setup` is used in a lot of plugins which have it responsible for initializing the plugin as well as configuring it. Due to this semantic difference, I felt using `.setup` was overloading the term.

**Comment by Diablo-D3** [comment]
Works for me. I do actually miss when merely installing a .vim script with `au`s in it was enough.

**Comment by RaafatTurki** [comment]
@RRethy Historical baggage aside, a single entry point that kicks the plugin into action would give users better control over load order and lazy loading.

> Having to install a plugin and call `require('plugin_name').setup({})` a bunch of times ...

Most plugins provide a plugin spec that does this part automatically like so:
```lua
  { 
    'RRethy/vim-illuminate',
    config = function()
       require 'illuminate'.setup { ... }
    end
  },
```
It's worth noting that in order to disable setup-less plugins on minimal plugin managers uninstalling is the only option, in contrast with the above it's as easy as commenting `setup()`.

It doesn't have to be named `setup` ofc. this is obviously a breaking change, But I've seen other plugins go through this just fine.

Installing and starting a plugin should be 2 separate things, Kindly reconsider.

**Comment by RRethy** [comment]
> Most plugins provide a plugin spec that does this part automatically like so:

>   { 
>    'RRethy/vim-illuminate',
>    config = function()
>       require 'illuminate'.setup { ... }
>    end
>  },

Your description doesn't match the code sample, and even if it did, wouldn't that mean it's the same as not having the setup method in the first place just with extra steps?

> It's worth noting that in order to disable setup-less plugins on some plugin managers uninstalling is the only option, in contrast with the above it's as easy as commenting setup().

That's a poorly written plugin manager or a misconfigured plugin manager. Neovim has the ability to do this builtin with `opt/` plugins.

> Installing and starting a plugin should be 2 separate things

It is. Installing vim-illuminate won't start the plugin. Loading the plugin will however start the plugin which conforms to the Neovim user manual.

**Comment by Kerwood** [comment]
I think that @RaafatTurki did not provide the best Lazy example to prove his point.
If `vim-illuminate` was using the `.setup()` method, you would just give it a map with the options to configure, like with every other plugin.
```lua
{
  "RRethy/vim-illuminate",
  opts = {
    delay = 100,
  },
}
```

But because `vim-illuminate` does not follow the unwritten nvim plugin naming convention, it becomes a special case that needs its own snowflake configuration method.
```lua
{
  "RRethy/vim-illuminate",
  config = function()
    require("illuminate").configure {
      delay = 100,
    }
  end,
}
```

**Comment by RRethy** [comment]
> I think that @RaafatTurki did not provide the best Lazy example to prove his point. If `vim-illuminate` was using the `.setup()` method, you would just give it a map with the options to configure, like with every other plugin.
> 
> ```lua
> {
>   "RRethy/vim-illuminate",
>   opts = {
>     delay = 100,
>   },
> }
> ```
> 
> But because `vim-illuminate` does not follow the unwritten nvim plugin naming convention, it becomes a special case that needs its own snowflake configuration method.
> 
> ```lua
> {
>   "RRethy/vim-illuminate",
>   config = function()
>     require("illuminate").configure {
>       delay = 100,
>     }
>   end,
> }
> ```

It is not an `unwritten nvim plugin naming convention`. Lazy nvim is a open source plugin manager, it doesn't set the way plugins are written.

See https://github.com/nvim-neorocks/nvim-best-practices?tab=readme-ov-file#zap-initialization and https://mrcjkb.dev/posts/2023-08-22-setup.html.

**Comment by Kerwood** [comment]
If its not an "unwritten naming convention" it must be a "written naming convention" then.. jk :smiley:

As it says:
> Dont force users to call a setup function in order to be able to use your plugin.

Which you shouldn't and currently do not do. It would just be nice if the, some what badly named, `setup` function was used for configuration, as it would fit better with the ecosystem.

I get why you are reluctant to change, don't sweat it. It was just food for thought.
