### ISSUE TITLE
Feature request: Can I configure the plugin to highlight other occurences of current selection when in visual or select mode?

### ISSUE THREAD

**Issue by renauga** [RRethy/vim-illuminate#196]
I want the plugin to work like this:
1. When in visual mode, highlight the current selection - this can be disabled if there are too many occurences or the selection is too large.
2. Otherwise, work as it currently does.
How can I achieve this?

**Comment by RRethy** [comment]
You can use the `should_enable = function(bufnr) return true end,` field in the config. Just add your own logic to disable/enable.

**Comment by renauga** [comment]
But how do I change the string being illuminated? Currently, in visual mode, the reference under the cursor is illuminated, not the selection.

**Comment by RRethy** [comment]
You probably need a different plugin, vim-illuminate doesn't provide the functionality to highlight other occurrences of a visual selection.

**Comment by renauga** [comment]
I couldn't find a plugin for this.
It looks a like a good feature to add to vim-illuminate. It's similar to the current use of the plugin and makes more sense in visual mode.

**Comment by Dima-369** [comment]
I am also very interested in this feature, and sadly, this was closed. So, I just let AI do the implementation, since I love having this from the JetBrains' IDEs.

Here is my fork: https://github.com/Dima-369/vim-illuminate

I am not experienced in nvim plugin development, thus I won't submit a PR. It works for me, and if someone likes, feel free to create a PR for this based on my changed code 🙂 

![Image](https://github.com/user-attachments/assets/7990d39e-cf11-4427-95d4-0812f28457df)
