### ISSUE TITLE
How to install your VIM Plugin?

### ISSUE THREAD

**Issue by tdimnet** [RRethy/vim-illuminate#21]
Hi there,

I am brand new to the vim world and I am trying to install your plugin without using any plugin manager.
I found and followed this tutorial: https://howchoo.com/g/ztmyntqzntm/how-to-install-vim-plugins-without-a-plugin-manager but at the end it seems it does not work and I am not able to use your plugin. 

It seems that my runtimepath has been setted up correctly and I also cloned your repo within my own .vim/bundle

Do you have a piece of advice for me?

Thx.

**Comment by RRethy** [comment]
So a few things:

1. If you would be able to provide your .vimrc I can take a look to see if it has anything that could cause it to fail since the steps in the article should work. If I had to guess (which might be wrong, I would need to see your .vimrc), I would assume `set runtimepath^=~/.vim/bundle/vim-illuminate` has a misspelling.

2. If you are starting out with Vim, I would recommend using a plugin/package manager such as [minpac](https://github.com/k-takata/minpac) or [vim-plug](https://github.com/junegunn/vim-plug) since it will make things a lot easier, then as you learn more about vim you ca move to native support (explained in point 3). I would recommend my package manager but unfortunately it is not yet finished :/

3. That article is out of date with the current way to install plugins. Currently, Vim has support for packages (see `:help packages`) which means you won't need the `set runtimepath^=...` inside your .vimrc. You can instead run:

```
mkdir -p ~/.vim/pack/plugs/start
cd ~/.vim/pack/plugs/start
git clone git@github.com:RRethy/vim-illuminate.git
```

Then there is no modification to the .vimrc and the plugin will *just work*.

If you want to learn more about packages which is the recommended way to install plugins, try [this article](https://shapeshed.com/vim-packages/) or try running `:help packages` in vim.

I'll close this issue in two days if I don't hear back since I will assume you got it fixed.

Good luck.

**Comment by tdimnet** [comment]
Many thanks for your answer!
I did what you explained and it works now :).

I close my issue.
