### ISSUE TITLE
Illuminate word under cursor only if there is another occurrence 

### ISSUE THREAD

**Issue by nitasn** [RRethy/vim-illuminate#28]
I would find this plugin most helpful if, as the title says,
illumination of the word under the cursor would mean there is a place to jump to with # \ *.
If this could be done, it would make the plugin very helpful to me and would be the reason for me to use it :)

**Comment by RRethy** [comment]
You may find this setting useful:

```vim
let g:Illuminate_highlightUnderCursor = 0
```

Checkout the docs for a description of this setting.

That being said, there is a few problems with your request:

1. The mechanism that is used under the hood is `:h matchadd()`, it doesn't return of inform the caller of the number of matches. In order to match only if others are matched would require preemptively calling `:h search()` with a regex that avoids matching the pattern under the cursor (the regex can be found [here](https://github.com/RRethy/vim-illuminate/blob/7ca9b415f02545278d623c0de535226e80a79e38/autoload/illuminate.vim#L101)). However, this is a potentially large overhead for very little return.

2. `#*` rely on `<cword>` while illuminate does not (illuminate is more accurate, see #3 for a how it is more accurate). Since they do not necessarily match the same thing, having illuminate match does not imply there is a match for `#` or `*` (and vice-versa).

**Comment by RRethy** [comment]
I'm going to close this since I don't see any progress on your branch and this isn't a feature I would implement since I think the overhead of the additional `search()` call and added complexity is not worth the return.
