### ISSUE TITLE
Words containing dashes are treated as 2 different words

### ISSUE THREAD

**Issue by mectos** [RRethy/vim-illuminate#38]
Words which contain dashes (happens a lot when working with CSS) such as:
text-decoration and border-top, are treated as 2 different words. i.e. it illuminates the first word, the dash is being ignored, and then it illuminates the second word.
I must add that it doesn't happen with words which contain underscores, only with dashes.

Thank you in advance :)

**Comment by RRethy** [comment]
This is due to your `:h 'iskeyword'` option, vim-illuminate will use it to determine word boundaries. Running `:set iskeyword+=-` will get the desired behaviour. I think you (or a plugin) have modified `'iskeyword'` and removed `-` from it since the dash will be there by default so double check everywhere to ensure you aren't messing with `'iskeyword'` elsewhere.

**Comment by mectos** [comment]
Thank you very much, you were right!
