### ISSUE TITLE
Don't override the highlight of hexokinase

### ISSUE THREAD

**Issue by kevinhwang91** [RRethy/vim-illuminate#46]
No matter the priority of highlight what I set, illuminate always override the highlight of hexokinase.
![image](https://user-images.githubusercontent.com/17562139/84031394-2ce54e00-a9c8-11ea-84f5-257c4953a05e.png)

Maybe add a blacklist for some specified pattern?

**Comment by RRethy** [comment]
Unfortunately this cannot be changed based on the highlight priority since hexokinase uses `nvim_buf_add_highlight` to place highlights on the buffer which does not utilize the priority mechanism that is used with matchadd and matchaddpos. In terms of a black list, this also would not work because illuminate does not place highlights down manually, it does so using matchadd which matches a single pattern so any blacklist would have to be combined with the main pattern with backreferences (and even then I'm not sure if it would work).

That being said, to fix the example in your screenshot, you can use `let g:Illuminate_highlightUnderCursor = 0`.

**Comment by kevinhwang91** [comment]
I used https://github.com/neoclide/coc-highlight before, which contains the feature of illuminate and hexokinase, also use rpc to call `nvim_buf_add_highlight` to highlight, but it can handle the override color.

I think illuminate and hexokinase are written by the same author, they should get along with each other.

**Comment by RRethy** [comment]
They do get a long with each other, they each perform their function, it just so happens the function of vim-illuminate is to `[highlight] other uses of the word under the cursor` which can sometimes be colour values. While you say coc-highlight handles the override, I would argue it is backwards to disable the curword matching for the colour highlighting, just look at vim-matchup (vim-matchup would take precedence). vim-illuminate is highlighting temporary locations in your code while vim-hexokinase is building on top of the syntax highlight. On top of that, coc-highlight uses nvim_buf_add_highlight for both whereas vim-illuminate uses matchadd and was written before nvim_buf_add_highlight was implemented.

I think if coc-highlight does both illuminate and hexokinase, then you should just use it since it's clearly more suited to your needs.
