### ISSUE TITLE
CursorHold instead of CursorMoved

### ISSUE THREAD

**Issue by reportaman** [RRethy/vim-illuminate#77]
Please add a setting to use CursorHold instead of CursorMoved. That way a user can get a word's matches illuminated only if the cursor stabilizes on a word. IMO this should improve scroll performance, as it won't trigger drawing when cursor is moving around.

**Comment by RRethy** [comment]
Using `CursorHold` is almost always the wrong choice for a plugin since it's configured via `:h 'updatetime'` which defaults to 4seconds. You can configure the delay with `:h g:Illuminate_delay` which defaults to 0ms. Also, this plugin shouldn't have much of an impact if any on scrolling performance, it might be a red herring if you are feeling that scrolling is slow.
