### ISSUE TITLE
Still highlight when leave the current buffer in lsp mode.

### ISSUE THREAD

**Issue by LimbicSys** [RRethy/vim-illuminate#78]
![图片](https://user-images.githubusercontent.com/30319215/123608346-422a5600-d831-11eb-80fa-b0c41f49fb68.png)
The left cpp file was opened first. Then I opened a plain text file in the right window, the words in cpp file are still highlighted.
If I do not use this plug in lsp mode, it will not highligh the words when I leave the current buffer.

**Comment by RRethy** [comment]
That's intended behaviour. When using LSP, highlighting is done with `:h nvim_buf_add_highlight()` while non-lsp highlighting is done with `:h matchadd()`, the former adds highlighting to the buffer while the latter adds highlighting to the window. Since the latter adds highlighting to the window, it must be removed when leaving the window or it can become invalid.
